version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aspis
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=aspis_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ws-network
volumes:
  pgdata:

networks:
  ws-network:
 